name: Sync and Modify

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:

jobs:
  sync-and-modify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      #- name: Checkout Fork
       # uses: actions/checkout@v4
       # with:
        #  token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync with Upstream
        run: |
          gh repo sync ${{ github.repository }} --branch main --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Modify ipraioita.m3u
        run: |
          if [ -f "ipraioita.m3u" ]; then
            sed -i -E 's/(#EXTINF:[^,]*,)/\1 radio="true",/' ipraioita.m3u
          fi

      - name: Commit Changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ipraioita.m3u
          git commit -m "Modify ipraioita.m3u" || echo "No changes to commit"
          git push
